spring:
  application:
    name: fanout-learn
  rabbitmq:
    host: 47.113.219.144
    password: pinger1234567
    port: 5672
    username: ygz
    virtual-host: powernode # 虚拟主机
server:
  port: 9090
my:
  directExchangeName: exchange.direct
  directQueueAName: queue.direct.a
  directQueueBName: queue.direct.b